name: 'Amazon ECS "Run Task" Action for GitHub Actions'
description: 'Runs an Amazon ECS task'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  task-definition:
    description: 'The name of ECS task definition'
    required: true
  cluster:
    description: "The name of the ECS cluster. Will default to the 'default' cluster"
    required: true
  launch-type:
    description: "The launch type of the ECS Task. Either EC2 or FARGATE. Defaults to EC2"
    required: false
  use-vpc:
    description: "The id of a VPC to use. Required when using the FARGATE launch type"
    required: false
  count:
    description: "The count of tasks to run. Will default to 1"
    required: false
  started-by:
    description: "The value of the task started-by"
    required: false
  wait-for-finish:
    description: "Whether to wait for tasks to reach stopped state. Will default to not waiting"
    required: false
  wait-for-minutes:
    description: 'How long to wait for the task reach stopped state, in minutes (default: 30 minutes, max: 6 hours).'
    required: false
outputs:
  task-definition-arn:
    description: 'The ARN of the registered ECS task definition'
  task-arn:
    description: 'The ARN of the ECS task'
runs:
  using: 'node12'
  main: 'dist/index.js'
